import type {
  AiAlert,
  CommandCenterStats,
  Department,
  DisciplinaryCase,
  Employee,
  EmployeeKpi,
  ExpenseClaim,
  JobApplication,
  KpiMetric,
  PayrollInvoice,
  PermissionConfig,
  RecruitmentRequest,
  Suggestion,
  TrainingAssessment,
  TrainingProgram,
  WarningCase,
} from './types';

export const DEPARTMENT_LABELS: Record<Department, string> = {
  inspection: 'Inspection',
  maintenance: 'Maintenance',
  leasing: 'Leasing',
  customer_service: 'Customer Service',
  hr: 'HR',
  it: 'IT',
  finance: 'Finance',
};

export const employees: Employee[] = [
  {
    id: 'emp-001',
    employeeNumber: 'CX-1001',
    fullName: 'Sarah Chen',
    email: 'sarah.chen@crossub.com',
    mobile: '+61 412 345 678',
    dateOfBirth: '1990-03-15',
    age: 36,
    gender: 'Female',
    nationality: 'Australian',
    address: '42 Collins St, Melbourne VIC 3000',
    department: 'inspection',
    position: 'Senior Property Inspector',
    status: 'active',
    hireDate: '2022-06-01',
    salaryModel: 'per_task',
    baseSalary: 0,
    currency: 'AUD',
    managerId: 'emp-010',
    profileComplete: true,
    emergencyContact: {
      name: 'James Chen',
      relationship: 'Spouse',
      mobile: '+61 412 999 888',
      email: 'james.chen@email.com',
    },
    documents: {
      passport: true,
      driverLicence: true,
      nationalId: true,
      utilityBill: true,
      degree: true,
      resume: true,
      contract: true,
      nda: true,
    },
  },
  {
    id: 'emp-002',
    employeeNumber: 'CX-1002',
    fullName: 'Marcus Wong',
    email: 'marcus.wong@crossub.com',
    mobile: '+60 12 345 6789',
    dateOfBirth: '1988-11-22',
    age: 37,
    gender: 'Male',
    nationality: 'Malaysian',
    address: '15 Jalan Ampang, Kuala Lumpur',
    department: 'leasing',
    position: 'Leasing Consultant',
    status: 'active',
    hireDate: '2021-09-15',
    salaryModel: 'commission',
    baseSalary: 3500,
    currency: 'MYR',
    managerId: 'emp-011',
    profileComplete: true,
    emergencyContact: {
      name: 'Lisa Wong',
      relationship: 'Sister',
      mobile: '+60 12 888 7777',
      email: 'lisa.wong@email.com',
    },
    documents: { passport: true, resume: true, contract: true, nda: true },
  },
  {
    id: 'emp-003',
    employeeNumber: 'CX-1003',
    fullName: 'Emily Roberts',
    email: 'emily.roberts@crossub.com',
    mobile: '+61 423 456 789',
    dateOfBirth: '1995-07-08',
    age: 30,
    gender: 'Female',
    nationality: 'Australian',
    address: '88 George St, Sydney NSW 2000',
    department: 'maintenance',
    position: 'Maintenance Coordinator',
    status: 'probation',
    hireDate: '2026-02-01',
    probationEnd: '2026-08-01',
    salaryModel: 'monthly',
    baseSalary: 6200,
    currency: 'AUD',
    managerId: 'emp-012',
    profileComplete: false,
    emergencyContact: {
      name: 'Tom Roberts',
      relationship: 'Father',
      mobile: '+61 423 111 222',
      email: 'tom.roberts@email.com',
    },
    documents: { passport: true, resume: true },
  },
  {
    id: 'emp-004',
    employeeNumber: 'CX-1004',
    fullName: 'David Kim',
    email: 'david.kim@crossub.com',
    mobile: '+65 9123 4567',
    dateOfBirth: '1992-01-30',
    age: 34,
    gender: 'Male',
    nationality: 'Singaporean',
    address: '10 Marina Blvd, Singapore',
    department: 'customer_service',
    position: 'Customer Service Lead',
    status: 'active',
    hireDate: '2020-04-10',
    salaryModel: 'hybrid',
    baseSalary: 4800,
    currency: 'SGD',
    profileComplete: true,
    emergencyContact: {
      name: 'Anna Kim',
      relationship: 'Spouse',
      mobile: '+65 9876 5432',
      email: 'anna.kim@email.com',
    },
    documents: { passport: true, contract: true, nda: true, degree: true },
  },
  {
    id: 'emp-005',
    employeeNumber: 'CX-1005',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@crossub.com',
    mobile: '+61 434 567 890',
    dateOfBirth: '1998-12-05',
    age: 27,
    gender: 'Female',
    nationality: 'Indian',
    address: '25 Queen St, Brisbane QLD 4000',
    department: 'inspection',
    position: 'Junior Inspector (Training)',
    status: 'onboarding',
    hireDate: '2026-05-15',
    salaryModel: 'per_task',
    baseSalary: 0,
    currency: 'AUD',
    managerId: 'emp-001',
    profileComplete: false,
    emergencyContact: {
      name: 'Raj Sharma',
      relationship: 'Father',
      mobile: '+61 434 000 111',
      email: 'raj.sharma@email.com',
    },
    documents: { passport: true, resume: true },
  },
  {
    id: 'emp-006',
    employeeNumber: 'CX-1006',
    fullName: 'James O\'Brien',
    email: 'james.obrien@crossub.com',
    mobile: '+61 445 678 901',
    dateOfBirth: '1985-05-20',
    age: 41,
    gender: 'Male',
    nationality: 'Australian',
    address: '7 Flinders Lane, Melbourne VIC 3000',
    department: 'it',
    position: 'IT Systems Administrator',
    status: 'suspended',
    hireDate: '2019-11-01',
    salaryModel: 'monthly',
    baseSalary: 8500,
    currency: 'AUD',
    profileComplete: true,
    emergencyContact: {
      name: 'Kate O\'Brien',
      relationship: 'Spouse',
      mobile: '+61 445 222 333',
      email: 'kate.obrien@email.com',
    },
    documents: { passport: true, contract: true, nda: true },
  },
];

export const payrollInvoices: PayrollInvoice[] = [
  {
    id: 'pay-001',
    employeeId: 'emp-001',
    employeeName: 'Sarah Chen',
    period: 'May 2026',
    currency: 'AUD',
    baseSalary: 0,
    commission: 0,
    kpiBonus: 450,
    allowances: 120,
    total: 3840,
    status: 'pending_employee',
    inspectionsCompleted: 42,
  },
  {
    id: 'pay-002',
    employeeId: 'emp-002',
    employeeName: 'Marcus Wong',
    period: 'May 2026',
    currency: 'MYR',
    baseSalary: 3500,
    commission: 8200,
    kpiBonus: 600,
    allowances: 200,
    total: 12500,
    status: 'pending_finance',
  },
  {
    id: 'pay-003',
    employeeId: 'emp-004',
    employeeName: 'David Kim',
    period: 'May 2026',
    currency: 'SGD',
    baseSalary: 4800,
    commission: 0,
    kpiBonus: 320,
    allowances: 150,
    total: 5270,
    status: 'approved',
  },
  {
    id: 'pay-004',
    employeeId: 'emp-003',
    employeeName: 'Emily Roberts',
    period: 'May 2026',
    currency: 'AUD',
    baseSalary: 6200,
    commission: 0,
    kpiBonus: 0,
    allowances: 80,
    total: 6280,
    status: 'draft',
  },
];

export const departmentKpis: KpiMetric[] = [
  { id: 'kpi-1', department: 'inspection', name: 'Inspections Completed', target: 500, actual: 472, unit: 'count', period: 'May 2026', trend: 'stable' },
  { id: 'kpi-2', department: 'inspection', name: 'Complaint Rate', target: 2, actual: 3.1, unit: '%', period: 'May 2026', trend: 'down' },
  { id: 'kpi-3', department: 'maintenance', name: 'Response Time', target: 4, actual: 3.2, unit: 'hours', period: 'May 2026', trend: 'up' },
  { id: 'kpi-4', department: 'maintenance', name: 'Completion Rate', target: 95, actual: 91, unit: '%', period: 'May 2026', trend: 'down' },
  { id: 'kpi-5', department: 'leasing', name: 'Conversion Rate', target: 35, actual: 38, unit: '%', period: 'May 2026', trend: 'up' },
  { id: 'kpi-6', department: 'leasing', name: 'Vacancy Days', target: 21, actual: 18, unit: 'days', period: 'May 2026', trend: 'up' },
  { id: 'kpi-7', department: 'customer_service', name: 'Ticket Closure Rate', target: 90, actual: 87, unit: '%', period: 'May 2026', trend: 'stable' },
];

export const employeeKpis: EmployeeKpi[] = [
  {
    employeeId: 'emp-001',
    employeeName: 'Sarah Chen',
    department: 'inspection',
    score: 92,
    metrics: [
      { name: 'Inspections', value: 42, target: 40 },
      { name: 'Complaint Rate', value: 1.2, target: 2 },
      { name: 'Completion Speed', value: 95, target: 90 },
    ],
    riskLevel: 'none',
  },
  {
    employeeId: 'emp-006',
    employeeName: 'James O\'Brien',
    department: 'it',
    score: 58,
    metrics: [
      { name: 'Ticket Resolution', value: 72, target: 90 },
      { name: 'Response Time', value: 6.5, target: 4 },
      { name: 'Customer Satisfaction', value: 65, target: 85 },
    ],
    riskLevel: 'high',
  },
  {
    employeeId: 'emp-003',
    employeeName: 'Emily Roberts',
    department: 'maintenance',
    score: 74,
    metrics: [
      { name: 'Response Time', value: 4.8, target: 4 },
      { name: 'Completion Rate', value: 88, target: 95 },
    ],
    riskLevel: 'medium',
  },
];

export const recruitmentRequests: RecruitmentRequest[] = [
  {
    id: 'rec-001',
    department: 'inspection',
    position: 'Property Inspector',
    reason: 'staff_shortage',
    requestedBy: 'AI Workforce Planner',
    status: 'management_approval',
    aiGenerated: true,
    applicants: 0,
    shortlisted: 0,
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'rec-002',
    department: 'leasing',
    position: 'Senior Leasing Consultant',
    reason: 'expansion',
    requestedBy: 'Marcus Wong',
    status: 'published',
    aiGenerated: false,
    applicants: 24,
    shortlisted: 6,
    createdAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'rec-003',
    department: 'customer_service',
    position: 'Customer Service Agent',
    reason: 'replacement',
    requestedBy: 'David Kim',
    status: 'hr_review',
    aiGenerated: false,
    applicants: 12,
    shortlisted: 3,
    createdAt: '2026-05-28T14:00:00Z',
  },
];

export const jobApplications: JobApplication[] = [
  { id: 'app-001', recruitmentId: 'rec-002', candidateName: 'Alex Turner', email: 'alex.t@email.com', aiScore: 87, stage: 'manager_interview', appliedAt: '2026-05-12T09:00:00Z' },
  { id: 'app-002', recruitmentId: 'rec-002', candidateName: 'Nina Patel', email: 'nina.p@email.com', aiScore: 91, stage: 'offer', appliedAt: '2026-05-11T11:00:00Z' },
  { id: 'app-003', recruitmentId: 'rec-003', candidateName: 'Chris Lee', email: 'chris.l@email.com', aiScore: 72, stage: 'ai_interview', appliedAt: '2026-05-29T16:00:00Z' },
];

export const trainingPrograms: TrainingProgram[] = [
  { id: 'tr-001', title: 'Inspector Licence Preparation', type: 'position_specific', department: 'inspection', dueDate: '2026-07-01', assignedCount: 3, completedCount: 1, aiTrainer: true },
  { id: 'tr-002', title: 'Fair Work Compliance 2026', type: 'compliance', dueDate: '2026-06-30', assignedCount: 48, completedCount: 35, aiTrainer: true },
  { id: 'tr-003', title: 'CROSSUB Platform — Maintenance Module', type: 'system', department: 'maintenance', dueDate: '2026-06-15', assignedCount: 8, completedCount: 6, aiTrainer: true },
  { id: 'tr-004', title: 'Property Industry Standards', type: 'industry', dueDate: '2026-08-01', assignedCount: 20, completedCount: 12, aiTrainer: false },
];

export const trainingAssessments: TrainingAssessment[] = [
  { id: 'ta-001', trainingId: 'tr-002', employeeId: 'emp-001', employeeName: 'Sarah Chen', score: 94, passed: true, completedAt: '2026-05-20T10:00:00Z' },
  { id: 'ta-002', trainingId: 'tr-001', employeeId: 'emp-005', employeeName: 'Priya Sharma', score: 78, passed: true, completedAt: '2026-06-02T14:00:00Z' },
];

export const warningCases: WarningCase[] = [
  {
    id: 'warn-001',
    employeeId: 'emp-006',
    employeeName: 'James O\'Brien',
    department: 'it',
    level: 2,
    trigger: 'low_kpi',
    status: 'ceo_approval',
    aiDraftReady: true,
    createdAt: '2026-05-25T09:00:00Z',
  },
  {
    id: 'warn-002',
    employeeId: 'emp-003',
    employeeName: 'Emily Roberts',
    department: 'maintenance',
    level: 1,
    trigger: 'complaints',
    status: 'manager_review',
    aiDraftReady: true,
    createdAt: '2026-06-03T11:00:00Z',
  },
];

export const disciplinaryCases: DisciplinaryCase[] = [
  {
    id: 'disc-001',
    employeeId: 'emp-006',
    employeeName: 'James O\'Brien',
    warningLevel: 2,
    status: 'pending_decision',
    suspended: true,
    legalRiskScore: 42,
    legalRiskSummary: 'Moderate Fair Work risk — ensure documented performance improvement plan and interview notes before termination decision.',
    interviewDate: '2026-06-05T10:00:00Z',
  },
];

export const expenseClaims: ExpenseClaim[] = [
  { id: 'exp-001', employeeId: 'emp-001', employeeName: 'Sarah Chen', title: 'Inspection travel — Western suburbs', amount: 186.5, currency: 'AUD', status: 'manager_review', submittedAt: '2026-06-04T08:00:00Z', receipts: 3 },
  { id: 'exp-002', employeeId: 'emp-002', employeeName: 'Marcus Wong', title: 'Client meeting catering', amount: 420, currency: 'MYR', status: 'finance_review', submittedAt: '2026-06-02T12:00:00Z', receipts: 2 },
  { id: 'exp-003', employeeId: 'emp-004', employeeName: 'David Kim', title: 'Training conference registration', amount: 350, currency: 'SGD', status: 'approved', submittedAt: '2026-05-28T09:00:00Z', receipts: 1 },
];

export const suggestions: Suggestion[] = [
  {
    id: 'sug-001',
    employeeId: 'emp-001',
    employeeName: 'Sarah Chen',
    title: 'Mobile inspection photo upload improvement',
    content: 'Allow batch upload of inspection photos to reduce time on-site.',
    category: 'system_improvement',
    aiCategory: 'System Improvement',
    forwardedTo: 'IT Department',
    status: 'reviewed',
    submittedAt: '2026-05-15T10:00:00Z',
  },
  {
    id: 'sug-002',
    employeeId: 'emp-004',
    employeeName: 'David Kim',
    title: 'Weekly team standup for CS',
    content: 'Short weekly sync would help coordinate escalations across shifts.',
    category: 'management_improvement',
    aiCategory: 'Management Improvement',
    forwardedTo: 'Management Team',
    status: 'rewarded',
    reward: 'Recognition Award',
    submittedAt: '2026-05-20T14:00:00Z',
  },
];

export const aiAlerts: AiAlert[] = [
  { id: 'alert-001', type: 'kpi_decline', title: 'KPI decline detected', description: 'James O\'Brien — IT ticket resolution below threshold for 3 consecutive weeks.', severity: 'critical', employeeId: 'emp-006', department: 'it', createdAt: '2026-06-04T06:00:00Z' },
  { id: 'alert-002', type: 'staff_shortage', title: 'Predicted staffing shortage', description: 'Inspection department may be understaffed by 2 FTE in July based on workload forecast.', severity: 'warning', department: 'inspection', createdAt: '2026-06-01T08:00:00Z' },
  { id: 'alert-003', type: 'training_due', title: 'Quarterly assessment due', description: '12 employees have not completed Fair Work Compliance 2026 training.', severity: 'warning', createdAt: '2026-06-03T09:00:00Z' },
  { id: 'alert-004', type: 'complaints', title: 'Complaint spike', description: 'Maintenance department complaint rate increased 40% this month.', severity: 'warning', department: 'maintenance', createdAt: '2026-06-02T11:00:00Z' },
  { id: 'alert-005', type: 'payroll', title: 'Payroll approvals pending', description: '3 payroll invoices awaiting finance approval for May 2026.', severity: 'info', createdAt: '2026-06-05T08:00:00Z' },
];

export const commandCenterStats: CommandCenterStats = {
  totalEmployees: 48,
  onProbation: 4,
  activeRecruitment: 3,
  trainingDue: 13,
  kpiAlerts: 5,
  warningCases: 2,
  upcomingReviews: 7,
  pendingPayroll: 4,
  pendingExpenses: 3,
  staffShortageAlerts: 1,
};

export const permissionConfigs: PermissionConfig[] = [
  { role: 'employee', label: 'Employee', canViewSalary: false, canViewPayroll: false, canViewKpi: false, canViewWarnings: false, canViewTermination: false, canApprovePayroll: false, canApproveWarnings: false, canTerminate: false },
  { role: 'department_manager', label: 'Department Manager', canViewSalary: true, canViewPayroll: false, canViewKpi: true, canViewWarnings: true, canViewTermination: false, canApprovePayroll: false, canApproveWarnings: true, canTerminate: false },
  { role: 'hr_manager', label: 'HR Manager', canViewSalary: true, canViewPayroll: true, canViewKpi: true, canViewWarnings: true, canViewTermination: true, canApprovePayroll: true, canApproveWarnings: true, canTerminate: false },
  { role: 'director', label: 'Director', canViewSalary: true, canViewPayroll: true, canViewKpi: true, canViewWarnings: true, canViewTermination: true, canApprovePayroll: true, canApproveWarnings: true, canTerminate: true },
  { role: 'ceo', label: 'CEO', canViewSalary: true, canViewPayroll: true, canViewKpi: true, canViewWarnings: true, canViewTermination: true, canApprovePayroll: true, canApproveWarnings: true, canTerminate: true },
];

export function getEmployeeById(id: string): Employee | undefined {
  return employees.find((e) => e.id === id);
}

export function formatDepartment(dept: Department): string {
  return DEPARTMENT_LABELS[dept] ?? dept;
}
